/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import main.*;

/**
 *
 * @author ACER
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        manager = new TextFiles();
        user = null;
        
        welcomeText.setText("Ayo login pls.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginFrame = new javax.swing.JFrame();
        usernameInput1 = new javax.swing.JTextField();
        Login1 = new javax.swing.JLabel();
        pswrdLbl1 = new javax.swing.JLabel();
        usernameLbl1 = new javax.swing.JLabel();
        pswrdInput1 = new javax.swing.JPasswordField();
        loginBtn1 = new javax.swing.JButton();
        signupFrame = new javax.swing.JFrame();
        usernameInput2 = new javax.swing.JTextField();
        signup = new javax.swing.JLabel();
        pswrdLbl2 = new javax.swing.JLabel();
        usernameLbl2 = new javax.swing.JLabel();
        pswrdInput2 = new javax.swing.JPasswordField();
        signupBtn = new javax.swing.JButton();
        mainLoginBtn = new javax.swing.JButton();
        welcomeText = new javax.swing.JLabel();
        mainSignupBtn = new javax.swing.JButton();

        usernameInput1.setText("username");

        Login1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Login1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login1.setText("Login");

        pswrdLbl1.setBackground(new java.awt.Color(70, 73, 75));
        pswrdLbl1.setText("password");

        usernameLbl1.setBackground(new java.awt.Color(70, 73, 75));
        usernameLbl1.setText("username");

        pswrdInput1.setText("password");

        loginBtn1.setText("login bro");

        javax.swing.GroupLayout loginFrameLayout = new javax.swing.GroupLayout(loginFrame.getContentPane());
        loginFrame.getContentPane().setLayout(loginFrameLayout);
        loginFrameLayout.setHorizontalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginFrameLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(loginBtn1))
                    .addGroup(loginFrameLayout.createSequentialGroup()
                        .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pswrdLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pswrdInput1)
                            .addComponent(usernameInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(Login1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginFrameLayout.setVerticalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFrameLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Login1)
                .addGap(35, 35, 35)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pswrdLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pswrdInput1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(loginBtn1)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        usernameInput2.setText("username");

        signup.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup.setText("Signup");

        pswrdLbl2.setBackground(new java.awt.Color(70, 73, 75));
        pswrdLbl2.setText("password");

        usernameLbl2.setBackground(new java.awt.Color(70, 73, 75));
        usernameLbl2.setText("username");

        pswrdInput2.setText("password");

        signupBtn.setText("signup fr");

        javax.swing.GroupLayout signupFrameLayout = new javax.swing.GroupLayout(signupFrame.getContentPane());
        signupFrame.getContentPane().setLayout(signupFrameLayout);
        signupFrameLayout.setHorizontalGroup(
            signupFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupFrameLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(signupFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupFrameLayout.createSequentialGroup()
                        .addGroup(signupFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pswrdLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(signupFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pswrdInput2)
                            .addComponent(usernameInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(signupFrameLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(signupBtn)))
                .addGap(42, 42, 42))
            .addGroup(signupFrameLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(signup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signupFrameLayout.setVerticalGroup(
            signupFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupFrameLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(signup)
                .addGap(28, 28, 28)
                .addGroup(signupFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signupFrameLayout.createSequentialGroup()
                        .addComponent(usernameLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pswrdLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupFrameLayout.createSequentialGroup()
                        .addComponent(usernameInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(pswrdInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(signupBtn)
                .addGap(72, 72, 72))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainLoginBtn.setText("Login");
        mainLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLoginBtnActionPerformed(evt);
            }
        });

        welcomeText.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        welcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText.setText("jLabel1");

        mainSignupBtn.setText("Signup");
        mainSignupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSignupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(mainSignupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLoginBtn)
                    .addComponent(mainSignupBtn))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainLoginBtnActionPerformed
        loginFrame.pack();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_mainLoginBtnActionPerformed

    private void mainSignupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSignupBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainSignupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public TextFiles manager;
    public User user;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login1;
    private javax.swing.JButton loginBtn1;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JButton mainLoginBtn;
    private javax.swing.JButton mainSignupBtn;
    private javax.swing.JPasswordField pswrdInput1;
    private javax.swing.JPasswordField pswrdInput2;
    private javax.swing.JLabel pswrdLbl1;
    private javax.swing.JLabel pswrdLbl2;
    private javax.swing.JLabel signup;
    private javax.swing.JButton signupBtn;
    private javax.swing.JFrame signupFrame;
    private javax.swing.JTextField usernameInput1;
    private javax.swing.JTextField usernameInput2;
    private javax.swing.JLabel usernameLbl1;
    private javax.swing.JLabel usernameLbl2;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
